apiVersion: v1
kind: Service
metadata:
  labels:
    app: example-app
    kustomize.toolkit.fluxcd.io/name: cluster-apps-prose-system-opa-envoy
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: example-app-service
  namespace: prose-system
spec:
  ports:
  - nodePort: 31204
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: example-app
  type: NodePort
status:
  loadBalancer: {}
