---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-jellyseerr
  namespace: flux-system
spec:
  path: ./evaluation/kubernetes/apps/test-sample-microservices/jellyseerr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: prose-k8s-home-ops
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: jellyseerr
      namespace: jellyseerr
  interval: 15m
  retryInterval: 1m
  timeout: 3m
