---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: online-boutique
  namespace: online-boutique
spec:
  interval: 15m
  chart:
    spec:
      chart: onlineboutique
      version: 0.6.0
      sourceRef:
        kind: HelmRepository
        name: online-boutique
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values: {}
