---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-prose-system-jaeger
  namespace: flux-system
spec:
  path: ./kubernetes/cluster-1/apps/prose-system/jaeger/jaeger
  prune: true
  sourceRef:
    kind: GitRepository
    name: prose-k8s-home-ops
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: jaeger
      namespace: prose-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
