---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: "golang-${app}"
spec:
  workloadSelector:
    labels:
      app: "${app}"
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: MERGE
        value:
          name: "envoy.filters.network.http_connection_manager"
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
            common_http_protocol_options:
              idle_timeout: 5s
