package main

import (
	"testing"
)

const data = `Ch8KDkFQUF9DT05UQUlORVJTEg0aC3Byb2R1Y3RwYWdlChoKCkNMVVNURVJfSUQSDBoKS3ViZXJuZXRlcwoeCgxJTlNUQU5DRV9JUFMSDhoMMTAuMjQ0LjEuMTUxChkKDUlTVElPX1ZFUlNJT04SCBoGMS4xOS4xCroBCgZMQUJFTFMSrwEqrAEKFAoDYXBwEg0aC3Byb2R1Y3RwYWdlCiQKGXNlY3VyaXR5LmlzdGlvLmlvL3Rsc01vZGUSBxoFaXN0aW8KMAofc2VydmljZS5pc3Rpby5pby9jYW5vbmljYWwtbmFtZRINGgtwcm9kdWN0cGFnZQorCiNzZXJ2aWNlLmlzdGlvLmlvL2Nhbm9uaWNhbC1yZXZpc2lvbhIEGgJ2MQoPCgd2ZXJzaW9uEgQaAnYxChoKB01FU0hfSUQSDxoNY2x1c3Rlci5sb2NhbAooCgROQU1FEiAaHnByb2R1Y3RwYWdlLXYxLTZjNWM5YzlkOS03ZGptegoXCglOQU1FU1BBQ0USChoIYm9va2luZm8KUwoFT1dORVISShpIa3ViZXJuZXRlczovL2FwaXMvYXBwcy92MS9uYW1lc3BhY2VzL2Jvb2tpbmZvL2RlcGxveW1lbnRzL3Byb2R1Y3RwYWdlLXYxCiEKDVdPUktMT0FEX05BTUUSEBoOcHJvZHVjdHBhZ2UtdjE=`

func TestDecodeXEnvoyPeerMetadataHeader(t *testing.T) {
	decoded, err := DecodeXEnvoyPeerMetadataHeader(data)
	if err != nil {
		t.Error(err)
		return
	}

	PrintXEnvoyPeerMetadataHeader(decoded)
}
