---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Toronto"
  METALLB_LB_RANGE: "192.168.49.20-192.168.49.50"
  METALLB_K8S_GATEWAY_ADDR: "192.168.49.20"
  METALLB_INGRESS_ADDR: "192.168.49.21"
  METALLB_JAEGER_QUERY: "192.168.49.22"
  METALLB_OTEL_COLLECTOR: "192.168.49.23"

  # TODO: replace to real secret domain
  SECRET_DOMAIN: "my-example.com"
