---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: online-boutique
  namespace: flux-system
spec:
  type: "oci"
  interval: 10m
  url: oci://us-docker.pkg.dev/online-boutique-ci/charts
