apiVersion: apps/v1
kind: Deployment
metadata:
  name: presidio
spec:
  selector:
    matchLabels:
      app: presidio
  template:
    metadata:
      labels:
        app: presidio
    spec:
      containers:
        - name: presidio
          image: ghcr.io/dettanym/prose-presidio:main
          imagePullPolicy: Always
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otlp.prose-system.svc.cluster.local:4318
          resources:
            requests:
              cpu: 10m
              memory: 500Mi
            limits:
              memory: 3Gi
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
