---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-jellyfin
  namespace: flux-system
spec:
  path: ./kubernetes/cluster-1/apps/test-sample-microservices/jellyfin/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: prose-k8s-home-ops
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: jellyfin
      namespace: jellyfin
  interval: 15m
  retryInterval: 1m
  timeout: 3m
