---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-prose-system-elasticsearch
  namespace: flux-system
spec:
  path: ./evaluation/kubernetes/apps/prose-system/elasticsearch/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: prose-k8s-home-ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
