---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-bookinfo-envoy-filter-details
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-istio-system-istiod
  path: ./evaluation/kubernetes/apps/test-sample-microservices/bookinfo/envoy-filter
  postBuild:
    substitute:
      app: details
  prune: true
  sourceRef:
    kind: GitRepository
    name: prose-k8s-home-ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-bookinfo-envoy-filter-ratings
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-istio-system-istiod
  path: ./evaluation/kubernetes/apps/test-sample-microservices/bookinfo/envoy-filter
  postBuild:
    substitute:
      app: ratings
  prune: true
  sourceRef:
    kind: GitRepository
    name: prose-k8s-home-ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-bookinfo-envoy-filter-reviews
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-istio-system-istiod
  path: ./evaluation/kubernetes/apps/test-sample-microservices/bookinfo/envoy-filter
  postBuild:
    substitute:
      app: reviews
  prune: true
  sourceRef:
    kind: GitRepository
    name: prose-k8s-home-ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-bookinfo-envoy-filter-productpage
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-istio-system-istiod
  path: ./evaluation/kubernetes/apps/test-sample-microservices/bookinfo/envoy-filter
  postBuild:
    substitute:
      app: productpage
  prune: true
  sourceRef:
    kind: GitRepository
    name: prose-k8s-home-ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-bookinfo-app
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-bookinfo-envoy-filter-details
    - name: cluster-apps-bookinfo-envoy-filter-ratings
    - name: cluster-apps-bookinfo-envoy-filter-reviews
    - name: cluster-apps-bookinfo-envoy-filter-productpage
  path: ./evaluation/kubernetes/apps/test-sample-microservices/bookinfo/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: prose-k8s-home-ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
