apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-prose-system-opa-envoy
  namespace: flux-system
spec:
  path: ./kubernetes/cluster-1/apps/prose-system/opa-envoy-plugin/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: prose-k8s-home-ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
