POST http://localhost:3000/batchanalyze
Content-Type: application/json
Accept: application/json

// expected result
//[
//  "PHONE_NUMBER",
//  "URL",
//  "EMAIL_ADDRESS",
//  "LOCATION",
//  "PERSON"
//]

{
  "json_to_analyze": {
    "key_a": {
      "key_a1": "My phone number is 212-121-1424"
    },
    "key_b": [
      "www.abc.com"
    ],
    "key_c": 3,
    "names": [
      "James Bond",
      "Clark Kent",
      "Hakeem Olajuwon",
      "No name here!"
    ],
    "users": [
      {
        "id": 1,
        "name": "John Doe",
        "email": "john.doe@example.com",
        "address": {
          "street": "123 Main St",
          "city": "Anytown",
          "state": "CA",
          "postal_code": "12345"
        }
      },
      {
        "id": 2,
        "name": "Jane Smith",
        "email": "jane.smith@example.com",
        "address": {
          "street": "456 Elm St",
          "city": "Somewhere",
          "state": "TX",
          "postal_code": "67890"
        }
      },
      {
        "id": 3,
        "name": "Alice Johnson",
        "email": "alice.johnson@example.com",
        "address": {
          "street": "789 Pine St",
          "city": "Elsewhere",
          "state": "NY",
          "postal_code": "11223"
        }
      }
    ]
  }
}

###

POST http://localhost:3000/batchanalyze
Content-Type: application/json
Accept: application/json

// expected output:
//[
//  "PHONE_NUMBER",
//  "URL",
//  "PERSON",
//  "LOCATION",
//  "DATE_TIME",
//  "NRP"
//]

{
  "json_to_analyze": {
    "key_F": {
      "key_a1": "My phone number is 212-121-1424"
    },
    "URL": "www.abc.com",
    "key_c": 3,
    "names": [
      "James Bond",
      "Clark Kent",
      "Hakeem Olajuwon",
      "No name here!"
    ],
    "address": "200 University Ave West, Waterloo ON N2L5G7, Canada",
    "DOB": "01-01-1989",
    "gender": "Female",
    "race": "Asian",
    "language": "French"
  }
}

###

POST http://localhost:3000/batchanalyze
Content-Type: application/json
Accept: application/json

//[
//  "US_DRIVER_LICENSE",
//  "PHONE_NUMBER",
//  "PERSON",
//  "US_BANK_NUMBER"
//]

{
  "json_to_analyze": {
    "ISBN-10": "1234567890",
    "ISBN-13": "123-1234567890",
    "author": "William Shakespeare",
    "id": 0,
    "language": "English",
    "pages": 200,
    "publisher": "PublisherA",
    "type": "paperback",
    "year": 1595
  }
}

###

POST http://localhost:3000/batchanalyze
Content-Type: application/json
Accept: application/json

//[
//  "US_DRIVER_LICENSE",
//  "PERSON"
//]

{
  "json_to_analyze": {
    "clustername": "null",
    "id": "0",
    "podname": "reviews-v3-77d94bd94b-jffmj",
    "reviews": [
      {
        "rating": {
          "color": "red",
          "stars": 5
        },
        "reviewer": "Reviewer1",
        "text": "An extremely entertaining play by Shakespeare. The slapstick humour is refreshing!"
      },
      {
        "rating": {
          "color": "red",
          "stars": 4
        },
        "reviewer": "Reviewer2",
        "text": "Absolutely fun and entertaining. The play lacks thematic depth when compared to other plays by Shakespeare."
      }
    ]
  }
}

###

POST http://localhost:3000/batchanalyze
Content-Type: application/json
Accept: application/json

//[]

{
  "json_to_analyze": {
    "id": 0,
    "ratings": {
      "Reviewer1": 5,
      "Reviewer2": 4
    }
  }
}

