---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bookinfo-plain
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-istio-system-istiod
  path: ./evaluation/kubernetes/apps/samples/bookinfo/_template
  targetNamespace: bookinfo-plain
  postBuild:
    substitute:
      ingress_name: bookinfo-plain
  prune: true
  sourceRef:
    kind: GitRepository
    name: prose-k8s-home-ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
