---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-online-boutique
  namespace: flux-system
spec:
  path: ./evaluation/kubernetes/apps/test-sample-microservices/online-boutique/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: prose-k8s-home-ops
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: online-boutique
      namespace: online-boutique
  interval: 30m
  retryInterval: 1m
  timeout: 3m
