---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-opa-istio-sidecar-config
  namespace: flux-system
spec:
  path: ./evaluation/kubernetes/apps/opa-istio/sidecar/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: prose-k8s-home-ops
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 3m
