---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-sockshop
  namespace: flux-system
spec:
  path: ./evaluation/kubernetes/apps/test-sample-microservices/sockshop/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: prose-k8s-home-ops
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta2
      kind: HelmRelease
      name: sockshop
      namespace: sockshop
  interval: 30m
  retryInterval: 1m
  timeout: 3m
