---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  interval: 15m
  chart:
    spec:
      chart: istiod
      version: 1.20.3
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
    crds: CreateReplace
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
    crds: CreateReplace
  uninstall:
    keepHistory: false
  values:
    global:
      imagePullPolicy: Always
      proxy_init:
        image: ghcr.io/dettanym/prose-istio-proxyv2:golang-filter-presidio
      proxy:
        image: ghcr.io/dettanym/prose-istio-proxyv2:golang-filter-presidio
    meshConfig:
      defaultProviders:
        tracing:
          - zipkin
      extensionProviders:
        - name: zipkin
          zipkin:
            service: jaeger-collector.prose-system.svc.cluster.local
            port: 9411