---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-pitstop
  namespace: flux-system
spec:
  path: ./kubernetes/cluster-1/apps/test-sample-microservices/pitstop/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: prose-k8s-home-ops
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: webapp
      namespace: test-sample-microservices
  interval: 30m
  retryInterval: 1m
  timeout: 3m
