---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
resources:
  - ./helmrelease.yaml
  - https://raw.githubusercontent.com/istio/istio/release-1.18/samples/addons/jaeger.yaml
  - jaeger-ingress.yaml
