apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.presidio.name }}
  labels:
    {{- include "charts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.presidio.service.type }}
  ports:
    - port: {{ .Values.presidio.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "charts.selectorLabels" . | nindent 4 }}
