---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-istio-system-envoy-filter
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-istio-system-istio-base
  path: ./evaluation/kubernetes/apps/istio-system/envoy-filter/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: prose-k8s-home-ops
  interval: 30m
  retryInterval: 1m
  timeout: 3m
