---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: jaeger
spec:
  interval: 15m
  chart:
    spec:
      chart: jaeger
      version: 1.0.2
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
    crds: CreateReplace
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
    crds: CreateReplace
  uninstall:
    keepHistory: false
  values:
    collector:
      service:
        zipkin:
          port: 9411
