apiVersion: v1
kind: Service
metadata:
  name: cached-presidio
spec:
  selector:
    app: cached-presidio
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
