apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: demo-instrumentation
spec:
  exporter:
    endpoint: http://demo-collector:4318
  propagators:
    - tracecontext
    - baggage
  #This is head sampling; done before creating the span.
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  #TODO: To change defaults for each auto-instrumented language (out of .NET, Java, Python, Node.js),
  # pass configuration here. From this page: https://opentelemetry.io/docs/k8s-operator/automatic/
  # check the links for each language.
  # As that page says, we still need to inject labels to the pods to autoinstrument them.
