---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: sockshop
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/microservices-demo/microservices-demo
  ref:
    commit: 9dff06fae4981921caec6a62393a6ebfce4b3e3f
  ignore: |
    # exclude all
    /*
    # include kubernetes directory
    !deploy/kubernetes/helm-chart
