apiVersion: apps/v1
kind: Deployment
metadata:
  name: prose-server
spec:
  selector:
    matchLabels:
      app: prose-server
  template:
    metadata:
      labels:
        app: prose-server
    spec:
      containers:
        - name: prose-server
          image: ghcr.io/dettanym/prose-opa-composer-server:main@sha256:06951be89fdaac0167685786b3031964e267bc6626d9203d91724a9a3493b9fc
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: grpc
              containerPort: 50051
              protocol: TCP
          volumeMounts:
            - mountPath: /app/tmp
              name: compiled-bundle
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            requests:
              cpu: 10m
              memory: 500Mi
            limits:
              memory: 3Gi
      volumes:
        - name: compiled-bundle
          emptyDir:
            sizeLimit: 1Gi
