---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-istio-system-istio-base
  namespace: flux-system
spec:
  path: ./evaluation/kubernetes/apps/istio-system/istio/istio-base
  prune: true
  sourceRef:
    kind: GitRepository
    name: prose-k8s-home-ops
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: istio-base
      namespace: istio-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-istio-system-istiod
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-istio-system-istio-base
  path: ./evaluation/kubernetes/apps/istio-system/istio/istiod
  prune: true
  sourceRef:
    kind: GitRepository
    name: prose-k8s-home-ops
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-istio-system-envoy-filter
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-istio-system-istiod
  path: ./evaluation/kubernetes/apps/istio-system/istio/envoy-filter
  prune: true
  sourceRef:
    kind: GitRepository
    name: prose-k8s-home-ops
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-istio-system-telemetry
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-istio-system-istiod
  path: ./evaluation/kubernetes/apps/istio-system/istio/telemetry
  prune: true
  sourceRef:
    kind: GitRepository
    name: prose-k8s-home-ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
