---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-echo-server
  namespace: flux-system
spec:
  path: ./evaluation/kubernetes/apps/default/echo-server/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: prose-k8s-home-ops
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta2
      kind: HelmRelease
      name: echo-server
      namespace: default
  interval: 30m
  retryInterval: 1m
  timeout: 3m
