apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: meshconfig
spec:
  meshConfig:
    enableTracing: true
    defaultConfig:
      tracing:
        zipkin:
          address: jaeger-collector.istio-system.svc.cluster.local:9411
        sampling: 100.0