apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: reviews-lua
  namespace: bookinfo
spec:
  workloadSelector:
    labels:
      app: reviews
  configPatches:
    # The first patch adds the lua filter to the listener/http connection manager
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          portNumber: 9080
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
      patch:
        operation: INSERT_BEFORE
        value: # lua filter specification
          name: envoy.lua
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
            inlineCode: |
              function envoy_on_request(request_handle)
                  request_handle:logWarn("hello world >> on request")
                  -- Log information about the request
                  request_handle:logWarn("  Authority: "..request_handle:headers():get(":authority"))
                  request_handle:logWarn("  Method: "..request_handle:headers():get(":method"))
                  request_handle:logWarn("  Path: "..request_handle:headers():get(":path"))
                  local streamInfo = request_handle:streamInfo()
                  request_handle:logWarn("Request handle downstream local address: "..streamInfo:downstreamLocalAddress()..", remote addr:"..streamInfo:downstreamDirectRemoteAddress())
              end

              function envoy_on_response(response_handle)
                  response_handle:logWarn("hello world >> on response")
                  -- Log response status code
                  response_handle:logWarn("  Response handle status: "..response_handle:headers():get(":status"))
                  local streamInfo = response_handle:streamInfo()
                  response_handle:logWarn("Response handle downstream local address: "..streamInfo:downstreamLocalAddress()..", remote addr:"..streamInfo:downstreamDirectRemoteAddress())
                  local body_len = response_handle:body():length()
                  response_handle:logWarn("  Body: "..response_handle:body():getBytes(0, body_len))
                  -- Make a call to the presidio service at presidio.prose-system.svc.cluster.local
                  local headers, body = response_handle:httpCall(
                          "prose_cluster",
                          {
                              [":method"] = "GET",
                              -- Create an HTTP body with a json_to_analyze field
                              [":path"] = "/batchanalyze",
                              [":authority"] = "presidio.prose-system.svc.cluster.local:3000",
                              ["Content-Type"] = "application/json"
                          }
                  ,
                          '{"json_to_analyze": { "URL": "www.abc.com"}}'
                  )
                  for key, value in pairs(headers) do
                      response_handle:logWarn("Presidio response header key: "..key..", Value: "..value)
                  end
                  for key, value in pairs(body) do
                      response_handle:logWarn("Presidio response body key: "..key..", Value: "..value)
                  end
              end
    # The second patch adds the cluster that is referenced by the lua code
    # cds match is omitted as a new cluster is being added
    - applyTo: CLUSTER
      match:
        context: SIDECAR_OUTBOUND
      patch:
        operation: ADD
        value: # cluster specification
          name: "prose_cluster"
          type: STRICT_DNS
          connect_timeout: 0.5s
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: lua_cluster
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: "presidio.prose-system.svc.cluster.local"
                          port_value: 3000