apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: meshconfig
spec:
  meshConfig:
    enableTracing: true
    defaultConfig:
      tracing: {}
      extensionProviders:
        name: zipkin
        zipkin:
          service: zipkin.istio-system.svc.cluster.local #jaeger-collector.prose-system.svc.cluster.local:9411
          port: 9411
---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mesh-default
  namespace: istio-system
spec:
  tracing:
    - providers:
        - name: zipkin
      randomSamplingPercentage: 100.00