apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: meshconfig
spec:
  meshConfig:
    enableTracing: true
    defaultConfig:
      tracing: {} # disabled MeshConfig tracing options
    extensionProviders:
      # add zipkin provider
      - name: zipkin
        zipkin:
          service: jaeger-collector.prose-system.svc.cluster.local
          port: 9411
---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mesh-default
  namespace: istio-system
spec:
  tracing:
    - providers:
        - name: zipkin