// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: privacy_profiles.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Map keys can't be enums so we used strings for purposes and PII types.
type PIIType int32

const (
	PIIType_CREDIT_CARD       PIIType = 0
	PIIType_NRP               PIIType = 1
	PIIType_US_ITIN           PIIType = 2
	PIIType_PERSON            PIIType = 3
	PIIType_US_BANK_NUMBER    PIIType = 4
	PIIType_US_PASSPORT       PIIType = 5
	PIIType_IP_ADDRESS        PIIType = 6
	PIIType_US_DRIVER_LICENSE PIIType = 7
	PIIType_CRYPTO            PIIType = 8
	PIIType_URL               PIIType = 9
	PIIType_PHONE_NUMBER      PIIType = 10
	PIIType_IBAN_CODE         PIIType = 11
	PIIType_DATE_TIME         PIIType = 12
	PIIType_LOCATION          PIIType = 13
	PIIType_EMAIL_ADDRESS     PIIType = 14
	PIIType_US_SSN            PIIType = 15
)

// Enum value maps for PIIType.
var (
	PIIType_name = map[int32]string{
		0:  "CREDIT_CARD",
		1:  "NRP",
		2:  "US_ITIN",
		3:  "PERSON",
		4:  "US_BANK_NUMBER",
		5:  "US_PASSPORT",
		6:  "IP_ADDRESS",
		7:  "US_DRIVER_LICENSE",
		8:  "CRYPTO",
		9:  "URL",
		10: "PHONE_NUMBER",
		11: "IBAN_CODE",
		12: "DATE_TIME",
		13: "LOCATION",
		14: "EMAIL_ADDRESS",
		15: "US_SSN",
	}
	PIIType_value = map[string]int32{
		"CREDIT_CARD":       0,
		"NRP":               1,
		"US_ITIN":           2,
		"PERSON":            3,
		"US_BANK_NUMBER":    4,
		"US_PASSPORT":       5,
		"IP_ADDRESS":        6,
		"US_DRIVER_LICENSE": 7,
		"CRYPTO":            8,
		"URL":               9,
		"PHONE_NUMBER":      10,
		"IBAN_CODE":         11,
		"DATE_TIME":         12,
		"LOCATION":          13,
		"EMAIL_ADDRESS":     14,
		"US_SSN":            15,
	}
)

func (x PIIType) Enum() *PIIType {
	p := new(PIIType)
	*p = x
	return p
}

func (x PIIType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PIIType) Descriptor() protoreflect.EnumDescriptor {
	return file_privacy_profiles_proto_enumTypes[0].Descriptor()
}

func (PIIType) Type() protoreflect.EnumType {
	return &file_privacy_profiles_proto_enumTypes[0]
}

func (x PIIType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PIIType.Descriptor instead.
func (PIIType) EnumDescriptor() ([]byte, []int) {
	return file_privacy_profiles_proto_rawDescGZIP(), []int{0}
}

type PurposeOfUse int32

const (
	PurposeOfUse_advertising    PurposeOfUse = 0
	PurposeOfUse_authentication PurposeOfUse = 1
	PurposeOfUse_shipping       PurposeOfUse = 2
	PurposeOfUse_payment        PurposeOfUse = 3
	PurposeOfUse_marketing      PurposeOfUse = 4
)

// Enum value maps for PurposeOfUse.
var (
	PurposeOfUse_name = map[int32]string{
		0: "advertising",
		1: "authentication",
		2: "shipping",
		3: "payment",
		4: "marketing",
	}
	PurposeOfUse_value = map[string]int32{
		"advertising":    0,
		"authentication": 1,
		"shipping":       2,
		"payment":        3,
		"marketing":      4,
	}
)

func (x PurposeOfUse) Enum() *PurposeOfUse {
	p := new(PurposeOfUse)
	*p = x
	return p
}

func (x PurposeOfUse) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PurposeOfUse) Descriptor() protoreflect.EnumDescriptor {
	return file_privacy_profiles_proto_enumTypes[1].Descriptor()
}

func (PurposeOfUse) Type() protoreflect.EnumType {
	return &file_privacy_profiles_proto_enumTypes[1]
}

func (x PurposeOfUse) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PurposeOfUse.Descriptor instead.
func (PurposeOfUse) EnumDescriptor() ([]byte, []int) {
	return file_privacy_profiles_proto_rawDescGZIP(), []int{1}
}

type SystemwideObservedProfile struct {
	state                         protoimpl.MessageState  `protogen:"open.v1"`
	SystemwideProcessingEntries   *PurposeBasedProcessing `protobuf:"bytes,1,opt,name=systemwideProcessingEntries,proto3" json:"systemwideProcessingEntries,omitempty"`
	ComposedServicesInternalFQDNs []string                `protobuf:"bytes,2,rep,name=ComposedServicesInternalFQDNs,proto3" json:"ComposedServicesInternalFQDNs,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *SystemwideObservedProfile) Reset() {
	*x = SystemwideObservedProfile{}
	mi := &file_privacy_profiles_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemwideObservedProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemwideObservedProfile) ProtoMessage() {}

func (x *SystemwideObservedProfile) ProtoReflect() protoreflect.Message {
	mi := &file_privacy_profiles_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemwideObservedProfile.ProtoReflect.Descriptor instead.
func (*SystemwideObservedProfile) Descriptor() ([]byte, []int) {
	return file_privacy_profiles_proto_rawDescGZIP(), []int{0}
}

func (x *SystemwideObservedProfile) GetSystemwideProcessingEntries() *PurposeBasedProcessing {
	if x != nil {
		return x.SystemwideProcessingEntries
	}
	return nil
}

func (x *SystemwideObservedProfile) GetComposedServicesInternalFQDNs() []string {
	if x != nil {
		return x.ComposedServicesInternalFQDNs
	}
	return nil
}

type SvcObservedProfile struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SvcInternalFQDN string                 `protobuf:"bytes,1,opt,name=svcInternalFQDN,proto3" json:"svcInternalFQDN,omitempty"`
	// repeated map_api_path_to_processing api_path_to_processing = 7;
	ObservedProcessingEntries *PurposeBasedProcessing `protobuf:"bytes,2,opt,name=observedProcessingEntries,proto3" json:"observedProcessingEntries,omitempty"`
	SpanID                    string                  `protobuf:"bytes,3,opt,name=spanID,proto3" json:"spanID,omitempty"`
	TraceID                   string                  `protobuf:"bytes,4,opt,name=traceID,proto3" json:"traceID,omitempty"`
	Purpose                   PurposeOfUse            `protobuf:"varint,5,opt,name=purpose,proto3,enum=privacy_profiles.PurposeOfUse" json:"purpose,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *SvcObservedProfile) Reset() {
	*x = SvcObservedProfile{}
	mi := &file_privacy_profiles_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SvcObservedProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SvcObservedProfile) ProtoMessage() {}

func (x *SvcObservedProfile) ProtoReflect() protoreflect.Message {
	mi := &file_privacy_profiles_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SvcObservedProfile.ProtoReflect.Descriptor instead.
func (*SvcObservedProfile) Descriptor() ([]byte, []int) {
	return file_privacy_profiles_proto_rawDescGZIP(), []int{1}
}

func (x *SvcObservedProfile) GetSvcInternalFQDN() string {
	if x != nil {
		return x.SvcInternalFQDN
	}
	return ""
}

func (x *SvcObservedProfile) GetObservedProcessingEntries() *PurposeBasedProcessing {
	if x != nil {
		return x.ObservedProcessingEntries
	}
	return nil
}

func (x *SvcObservedProfile) GetSpanID() string {
	if x != nil {
		return x.SpanID
	}
	return ""
}

func (x *SvcObservedProfile) GetTraceID() string {
	if x != nil {
		return x.TraceID
	}
	return ""
}

func (x *SvcObservedProfile) GetPurpose() PurposeOfUse {
	if x != nil {
		return x.Purpose
	}
	return PurposeOfUse_advertising
}

type PurposeBasedProcessing struct {
	state             protoimpl.MessageState              `protogen:"open.v1"`
	ProcessingEntries map[string]*DataItemAndThirdParties `protobuf:"bytes,1,rep,name=processingEntries,proto3" json:"processingEntries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PurposeBasedProcessing) Reset() {
	*x = PurposeBasedProcessing{}
	mi := &file_privacy_profiles_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurposeBasedProcessing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurposeBasedProcessing) ProtoMessage() {}

func (x *PurposeBasedProcessing) ProtoReflect() protoreflect.Message {
	mi := &file_privacy_profiles_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurposeBasedProcessing.ProtoReflect.Descriptor instead.
func (*PurposeBasedProcessing) Descriptor() ([]byte, []int) {
	return file_privacy_profiles_proto_rawDescGZIP(), []int{2}
}

func (x *PurposeBasedProcessing) GetProcessingEntries() map[string]*DataItemAndThirdParties {
	if x != nil {
		return x.ProcessingEntries
	}
	return nil
}

type DataItemAndThirdParties struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Entry         map[string]*ThirdParties `protobuf:"bytes,1,rep,name=entry,proto3" json:"entry,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataItemAndThirdParties) Reset() {
	*x = DataItemAndThirdParties{}
	mi := &file_privacy_profiles_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataItemAndThirdParties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataItemAndThirdParties) ProtoMessage() {}

func (x *DataItemAndThirdParties) ProtoReflect() protoreflect.Message {
	mi := &file_privacy_profiles_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataItemAndThirdParties.ProtoReflect.Descriptor instead.
func (*DataItemAndThirdParties) Descriptor() ([]byte, []int) {
	return file_privacy_profiles_proto_rawDescGZIP(), []int{3}
}

func (x *DataItemAndThirdParties) GetEntry() map[string]*ThirdParties {
	if x != nil {
		return x.Entry
	}
	return nil
}

type ThirdParties struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThirdParty    []string               `protobuf:"bytes,1,rep,name=thirdParty,proto3" json:"thirdParty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThirdParties) Reset() {
	*x = ThirdParties{}
	mi := &file_privacy_profiles_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThirdParties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThirdParties) ProtoMessage() {}

func (x *ThirdParties) ProtoReflect() protoreflect.Message {
	mi := &file_privacy_profiles_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThirdParties.ProtoReflect.Descriptor instead.
func (*ThirdParties) Descriptor() ([]byte, []int) {
	return file_privacy_profiles_proto_rawDescGZIP(), []int{4}
}

func (x *ThirdParties) GetThirdParty() []string {
	if x != nil {
		return x.ThirdParty
	}
	return nil
}

type Endpoints struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EndpointName    string                 `protobuf:"bytes,1,opt,name=endpointName,proto3" json:"endpointName,omitempty"`
	TraceID         string                 `protobuf:"bytes,2,opt,name=traceID,proto3" json:"traceID,omitempty"`
	SpanIDOfCall    string                 `protobuf:"bytes,3,opt,name=spanID_of_call,json=spanIDOfCall,proto3" json:"spanID_of_call,omitempty"`
	EndpointProfile *EndpointProfile       `protobuf:"bytes,4,opt,name=endpoint_profile,json=endpointProfile,proto3" json:"endpoint_profile,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Endpoints) Reset() {
	*x = Endpoints{}
	mi := &file_privacy_profiles_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoints) ProtoMessage() {}

func (x *Endpoints) ProtoReflect() protoreflect.Message {
	mi := &file_privacy_profiles_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoints.ProtoReflect.Descriptor instead.
func (*Endpoints) Descriptor() ([]byte, []int) {
	return file_privacy_profiles_proto_rawDescGZIP(), []int{5}
}

func (x *Endpoints) GetEndpointName() string {
	if x != nil {
		return x.EndpointName
	}
	return ""
}

func (x *Endpoints) GetTraceID() string {
	if x != nil {
		return x.TraceID
	}
	return ""
}

func (x *Endpoints) GetSpanIDOfCall() string {
	if x != nil {
		return x.SpanIDOfCall
	}
	return ""
}

func (x *Endpoints) GetEndpointProfile() *EndpointProfile {
	if x != nil {
		return x.EndpointProfile
	}
	return nil
}

type EndpointProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Direct        *DirectMessage         `protobuf:"bytes,1,opt,name=direct,proto3" json:"direct,omitempty"`
	Putgoing      *OutgoingMessage       `protobuf:"bytes,2,opt,name=putgoing,proto3" json:"putgoing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointProfile) Reset() {
	*x = EndpointProfile{}
	mi := &file_privacy_profiles_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointProfile) ProtoMessage() {}

func (x *EndpointProfile) ProtoReflect() protoreflect.Message {
	mi := &file_privacy_profiles_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointProfile.ProtoReflect.Descriptor instead.
func (*EndpointProfile) Descriptor() ([]byte, []int) {
	return file_privacy_profiles_proto_rawDescGZIP(), []int{6}
}

func (x *EndpointProfile) GetDirect() *DirectMessage {
	if x != nil {
		return x.Direct
	}
	return nil
}

func (x *EndpointProfile) GetPutgoing() *OutgoingMessage {
	if x != nil {
		return x.Putgoing
	}
	return nil
}

type DirectMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PiiPompliant  *PiiCompliant          `protobuf:"bytes,1,opt,name=pii_pompliant,json=piiPompliant,proto3" json:"pii_pompliant,omitempty"`
	PiiViolation  *PiiViolation          `protobuf:"bytes,2,opt,name=pii_violation,json=piiViolation,proto3" json:"pii_violation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectMessage) Reset() {
	*x = DirectMessage{}
	mi := &file_privacy_profiles_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectMessage) ProtoMessage() {}

func (x *DirectMessage) ProtoReflect() protoreflect.Message {
	mi := &file_privacy_profiles_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectMessage.ProtoReflect.Descriptor instead.
func (*DirectMessage) Descriptor() ([]byte, []int) {
	return file_privacy_profiles_proto_rawDescGZIP(), []int{7}
}

func (x *DirectMessage) GetPiiPompliant() *PiiCompliant {
	if x != nil {
		return x.PiiPompliant
	}
	return nil
}

func (x *DirectMessage) GetPiiViolation() *PiiViolation {
	if x != nil {
		return x.PiiViolation
	}
	return nil
}

type OutgoingMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Indirect      []*IndirectMessage     `protobuf:"bytes,1,rep,name=indirect,proto3" json:"indirect,omitempty"`
	Shared        []*SharedMessage       `protobuf:"bytes,2,rep,name=shared,proto3" json:"shared,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutgoingMessage) Reset() {
	*x = OutgoingMessage{}
	mi := &file_privacy_profiles_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutgoingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutgoingMessage) ProtoMessage() {}

func (x *OutgoingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_privacy_profiles_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutgoingMessage.ProtoReflect.Descriptor instead.
func (*OutgoingMessage) Descriptor() ([]byte, []int) {
	return file_privacy_profiles_proto_rawDescGZIP(), []int{8}
}

func (x *OutgoingMessage) GetIndirect() []*IndirectMessage {
	if x != nil {
		return x.Indirect
	}
	return nil
}

func (x *OutgoingMessage) GetShared() []*SharedMessage {
	if x != nil {
		return x.Shared
	}
	return nil
}

type IndirectMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpanID        string                 `protobuf:"bytes,1,opt,name=spanID,proto3" json:"spanID,omitempty"`
	CalleePath    string                 `protobuf:"bytes,2,opt,name=callee_path,json=calleePath,proto3" json:"callee_path,omitempty"`
	CalleeHost    string                 `protobuf:"bytes,3,opt,name=callee_host,json=calleeHost,proto3" json:"callee_host,omitempty"`
	PiiPompliant  *PiiCompliant          `protobuf:"bytes,4,opt,name=pii_pompliant,json=piiPompliant,proto3" json:"pii_pompliant,omitempty"`
	PiiViolation  *PiiViolation          `protobuf:"bytes,5,opt,name=pii_violation,json=piiViolation,proto3" json:"pii_violation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndirectMessage) Reset() {
	*x = IndirectMessage{}
	mi := &file_privacy_profiles_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndirectMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndirectMessage) ProtoMessage() {}

func (x *IndirectMessage) ProtoReflect() protoreflect.Message {
	mi := &file_privacy_profiles_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndirectMessage.ProtoReflect.Descriptor instead.
func (*IndirectMessage) Descriptor() ([]byte, []int) {
	return file_privacy_profiles_proto_rawDescGZIP(), []int{9}
}

func (x *IndirectMessage) GetSpanID() string {
	if x != nil {
		return x.SpanID
	}
	return ""
}

func (x *IndirectMessage) GetCalleePath() string {
	if x != nil {
		return x.CalleePath
	}
	return ""
}

func (x *IndirectMessage) GetCalleeHost() string {
	if x != nil {
		return x.CalleeHost
	}
	return ""
}

func (x *IndirectMessage) GetPiiPompliant() *PiiCompliant {
	if x != nil {
		return x.PiiPompliant
	}
	return nil
}

func (x *IndirectMessage) GetPiiViolation() *PiiViolation {
	if x != nil {
		return x.PiiViolation
	}
	return nil
}

type SharedMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SpanID         string                 `protobuf:"bytes,1,opt,name=spanID,proto3" json:"spanID,omitempty"`
	PiiPompliant   *PiiCompliant          `protobuf:"bytes,2,opt,name=pii_pompliant,json=piiPompliant,proto3" json:"pii_pompliant,omitempty"`
	PiiViolation   *PiiViolation          `protobuf:"bytes,3,opt,name=pii_violation,json=piiViolation,proto3" json:"pii_violation,omitempty"`
	ExternalDomain string                 `protobuf:"bytes,4,opt,name=external_domain,json=externalDomain,proto3" json:"external_domain,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SharedMessage) Reset() {
	*x = SharedMessage{}
	mi := &file_privacy_profiles_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SharedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharedMessage) ProtoMessage() {}

func (x *SharedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_privacy_profiles_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharedMessage.ProtoReflect.Descriptor instead.
func (*SharedMessage) Descriptor() ([]byte, []int) {
	return file_privacy_profiles_proto_rawDescGZIP(), []int{10}
}

func (x *SharedMessage) GetSpanID() string {
	if x != nil {
		return x.SpanID
	}
	return ""
}

func (x *SharedMessage) GetPiiPompliant() *PiiCompliant {
	if x != nil {
		return x.PiiPompliant
	}
	return nil
}

func (x *SharedMessage) GetPiiViolation() *PiiViolation {
	if x != nil {
		return x.PiiViolation
	}
	return nil
}

func (x *SharedMessage) GetExternalDomain() string {
	if x != nil {
		return x.ExternalDomain
	}
	return ""
}

type PiiViolation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pii           []PIIType              `protobuf:"varint,1,rep,packed,name=pii,proto3,enum=privacy_profiles.PIIType" json:"pii,omitempty"` //string violation reason = 2; //not used yet
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PiiViolation) Reset() {
	*x = PiiViolation{}
	mi := &file_privacy_profiles_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PiiViolation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PiiViolation) ProtoMessage() {}

func (x *PiiViolation) ProtoReflect() protoreflect.Message {
	mi := &file_privacy_profiles_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PiiViolation.ProtoReflect.Descriptor instead.
func (*PiiViolation) Descriptor() ([]byte, []int) {
	return file_privacy_profiles_proto_rawDescGZIP(), []int{11}
}

func (x *PiiViolation) GetPii() []PIIType {
	if x != nil {
		return x.Pii
	}
	return nil
}

type PiiCompliant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pii           []PIIType              `protobuf:"varint,1,rep,packed,name=pii,proto3,enum=privacy_profiles.PIIType" json:"pii,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PiiCompliant) Reset() {
	*x = PiiCompliant{}
	mi := &file_privacy_profiles_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PiiCompliant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PiiCompliant) ProtoMessage() {}

func (x *PiiCompliant) ProtoReflect() protoreflect.Message {
	mi := &file_privacy_profiles_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PiiCompliant.ProtoReflect.Descriptor instead.
func (*PiiCompliant) Descriptor() ([]byte, []int) {
	return file_privacy_profiles_proto_rawDescGZIP(), []int{12}
}

func (x *PiiCompliant) GetPii() []PIIType {
	if x != nil {
		return x.Pii
	}
	return nil
}

var File_privacy_profiles_proto protoreflect.FileDescriptor

const file_privacy_profiles_proto_rawDesc = "" +
	"\n" +
	"\x16privacy_profiles.proto\x12\x10privacy_profiles\x1a\x1bgoogle/protobuf/empty.proto\"\xcd\x01\n" +
	"\x19SystemwideObservedProfile\x12j\n" +
	"\x1bsystemwideProcessingEntries\x18\x01 \x01(\v2(.privacy_profiles.purposeBasedProcessingR\x1bsystemwideProcessingEntries\x12D\n" +
	"\x1dComposedServicesInternalFQDNs\x18\x02 \x03(\tR\x1dComposedServicesInternalFQDNs\"\x92\x02\n" +
	"\x12SvcObservedProfile\x12(\n" +
	"\x0fsvcInternalFQDN\x18\x01 \x01(\tR\x0fsvcInternalFQDN\x12f\n" +
	"\x19observedProcessingEntries\x18\x02 \x01(\v2(.privacy_profiles.purposeBasedProcessingR\x19observedProcessingEntries\x12\x16\n" +
	"\x06spanID\x18\x03 \x01(\tR\x06spanID\x12\x18\n" +
	"\atraceID\x18\x04 \x01(\tR\atraceID\x128\n" +
	"\apurpose\x18\x05 \x01(\x0e2\x1e.privacy_profiles.PurposeOfUseR\apurpose\"\xf8\x01\n" +
	"\x16purposeBasedProcessing\x12m\n" +
	"\x11processingEntries\x18\x01 \x03(\v2?.privacy_profiles.purposeBasedProcessing.ProcessingEntriesEntryR\x11processingEntries\x1ao\n" +
	"\x16ProcessingEntriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12?\n" +
	"\x05value\x18\x02 \x01(\v2).privacy_profiles.dataItemAndThirdPartiesR\x05value:\x028\x01\"\xbf\x01\n" +
	"\x17dataItemAndThirdParties\x12J\n" +
	"\x05entry\x18\x01 \x03(\v24.privacy_profiles.dataItemAndThirdParties.EntryEntryR\x05entry\x1aX\n" +
	"\n" +
	"EntryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.privacy_profiles.thirdPartiesR\x05value:\x028\x01\".\n" +
	"\fthirdParties\x12\x1e\n" +
	"\n" +
	"thirdParty\x18\x01 \x03(\tR\n" +
	"thirdParty\"\xbd\x01\n" +
	"\tendpoints\x12\"\n" +
	"\fendpointName\x18\x01 \x01(\tR\fendpointName\x12\x18\n" +
	"\atraceID\x18\x02 \x01(\tR\atraceID\x12$\n" +
	"\x0espanID_of_call\x18\x03 \x01(\tR\fspanIDOfCall\x12L\n" +
	"\x10endpoint_profile\x18\x04 \x01(\v2!.privacy_profiles.endpointProfileR\x0fendpointProfile\"\x89\x01\n" +
	"\x0fendpointProfile\x127\n" +
	"\x06direct\x18\x01 \x01(\v2\x1f.privacy_profiles.directMessageR\x06direct\x12=\n" +
	"\bputgoing\x18\x02 \x01(\v2!.privacy_profiles.outgoingMessageR\bputgoing\"\x9b\x01\n" +
	"\rdirectMessage\x12D\n" +
	"\rpii_pompliant\x18\x01 \x01(\v2\x1f.privacy_profiles.pii_compliantR\fpiiPompliant\x12D\n" +
	"\rpii_violation\x18\x02 \x01(\v2\x1f.privacy_profiles.pii_violationR\fpiiViolation\"\x89\x01\n" +
	"\x0foutgoingMessage\x12=\n" +
	"\bindirect\x18\x01 \x03(\v2!.privacy_profiles.indirectMessageR\bindirect\x127\n" +
	"\x06shared\x18\x02 \x03(\v2\x1f.privacy_profiles.sharedMessageR\x06shared\"\xf7\x01\n" +
	"\x0findirectMessage\x12\x16\n" +
	"\x06spanID\x18\x01 \x01(\tR\x06spanID\x12\x1f\n" +
	"\vcallee_path\x18\x02 \x01(\tR\n" +
	"calleePath\x12\x1f\n" +
	"\vcallee_host\x18\x03 \x01(\tR\n" +
	"calleeHost\x12D\n" +
	"\rpii_pompliant\x18\x04 \x01(\v2\x1f.privacy_profiles.pii_compliantR\fpiiPompliant\x12D\n" +
	"\rpii_violation\x18\x05 \x01(\v2\x1f.privacy_profiles.pii_violationR\fpiiViolation\"\xdc\x01\n" +
	"\rsharedMessage\x12\x16\n" +
	"\x06spanID\x18\x01 \x01(\tR\x06spanID\x12D\n" +
	"\rpii_pompliant\x18\x02 \x01(\v2\x1f.privacy_profiles.pii_compliantR\fpiiPompliant\x12D\n" +
	"\rpii_violation\x18\x03 \x01(\v2\x1f.privacy_profiles.pii_violationR\fpiiViolation\x12'\n" +
	"\x0fexternal_domain\x18\x04 \x01(\tR\x0eexternalDomain\"=\n" +
	"\rpii_violation\x12,\n" +
	"\x03pii\x18\x01 \x03(\x0e2\x1a.privacy_profiles.PII_typeR\x03pii\"=\n" +
	"\rpii_compliant\x12,\n" +
	"\x03pii\x18\x01 \x03(\x0e2\x1a.privacy_profiles.PII_typeR\x03pii*\xfb\x01\n" +
	"\bPII_type\x12\x0f\n" +
	"\vCREDIT_CARD\x10\x00\x12\a\n" +
	"\x03NRP\x10\x01\x12\v\n" +
	"\aUS_ITIN\x10\x02\x12\n" +
	"\n" +
	"\x06PERSON\x10\x03\x12\x12\n" +
	"\x0eUS_BANK_NUMBER\x10\x04\x12\x0f\n" +
	"\vUS_PASSPORT\x10\x05\x12\x0e\n" +
	"\n" +
	"IP_ADDRESS\x10\x06\x12\x15\n" +
	"\x11US_DRIVER_LICENSE\x10\a\x12\n" +
	"\n" +
	"\x06CRYPTO\x10\b\x12\a\n" +
	"\x03URL\x10\t\x12\x10\n" +
	"\fPHONE_NUMBER\x10\n" +
	"\x12\r\n" +
	"\tIBAN_CODE\x10\v\x12\r\n" +
	"\tDATE_TIME\x10\f\x12\f\n" +
	"\bLOCATION\x10\r\x12\x11\n" +
	"\rEMAIL_ADDRESS\x10\x0e\x12\n" +
	"\n" +
	"\x06US_SSN\x10\x0f*]\n" +
	"\fPurposeOfUse\x12\x0f\n" +
	"\vadvertising\x10\x00\x12\x12\n" +
	"\x0eauthentication\x10\x01\x12\f\n" +
	"\bshipping\x10\x02\x12\v\n" +
	"\apayment\x10\x03\x12\r\n" +
	"\tmarketing\x10\x042\xce\x01\n" +
	"\x16PrivacyProfileComposer\x12U\n" +
	"\x13PostObservedProfile\x12$.privacy_profiles.SvcObservedProfile\x1a\x16.google.protobuf.Empty\"\x00\x12]\n" +
	"\x14GetSystemWideProfile\x12\x16.google.protobuf.Empty\x1a+.privacy_profiles.SystemwideObservedProfile\"\x00B$Z\"privacy-profile-composer/pkg/protob\x06proto3"

var (
	file_privacy_profiles_proto_rawDescOnce sync.Once
	file_privacy_profiles_proto_rawDescData []byte
)

func file_privacy_profiles_proto_rawDescGZIP() []byte {
	file_privacy_profiles_proto_rawDescOnce.Do(func() {
		file_privacy_profiles_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_privacy_profiles_proto_rawDesc), len(file_privacy_profiles_proto_rawDesc)))
	})
	return file_privacy_profiles_proto_rawDescData
}

var file_privacy_profiles_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_privacy_profiles_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_privacy_profiles_proto_goTypes = []any{
	(PIIType)(0),                      // 0: privacy_profiles.PII_type
	(PurposeOfUse)(0),                 // 1: privacy_profiles.PurposeOfUse
	(*SystemwideObservedProfile)(nil), // 2: privacy_profiles.SystemwideObservedProfile
	(*SvcObservedProfile)(nil),        // 3: privacy_profiles.SvcObservedProfile
	(*PurposeBasedProcessing)(nil),    // 4: privacy_profiles.purposeBasedProcessing
	(*DataItemAndThirdParties)(nil),   // 5: privacy_profiles.dataItemAndThirdParties
	(*ThirdParties)(nil),              // 6: privacy_profiles.thirdParties
	(*Endpoints)(nil),                 // 7: privacy_profiles.endpoints
	(*EndpointProfile)(nil),           // 8: privacy_profiles.endpointProfile
	(*DirectMessage)(nil),             // 9: privacy_profiles.directMessage
	(*OutgoingMessage)(nil),           // 10: privacy_profiles.outgoingMessage
	(*IndirectMessage)(nil),           // 11: privacy_profiles.indirectMessage
	(*SharedMessage)(nil),             // 12: privacy_profiles.sharedMessage
	(*PiiViolation)(nil),              // 13: privacy_profiles.pii_violation
	(*PiiCompliant)(nil),              // 14: privacy_profiles.pii_compliant
	nil,                               // 15: privacy_profiles.purposeBasedProcessing.ProcessingEntriesEntry
	nil,                               // 16: privacy_profiles.dataItemAndThirdParties.EntryEntry
	(*emptypb.Empty)(nil),             // 17: google.protobuf.Empty
}
var file_privacy_profiles_proto_depIdxs = []int32{
	4,  // 0: privacy_profiles.SystemwideObservedProfile.systemwideProcessingEntries:type_name -> privacy_profiles.purposeBasedProcessing
	4,  // 1: privacy_profiles.SvcObservedProfile.observedProcessingEntries:type_name -> privacy_profiles.purposeBasedProcessing
	1,  // 2: privacy_profiles.SvcObservedProfile.purpose:type_name -> privacy_profiles.PurposeOfUse
	15, // 3: privacy_profiles.purposeBasedProcessing.processingEntries:type_name -> privacy_profiles.purposeBasedProcessing.ProcessingEntriesEntry
	16, // 4: privacy_profiles.dataItemAndThirdParties.entry:type_name -> privacy_profiles.dataItemAndThirdParties.EntryEntry
	8,  // 5: privacy_profiles.endpoints.endpoint_profile:type_name -> privacy_profiles.endpointProfile
	9,  // 6: privacy_profiles.endpointProfile.direct:type_name -> privacy_profiles.directMessage
	10, // 7: privacy_profiles.endpointProfile.putgoing:type_name -> privacy_profiles.outgoingMessage
	14, // 8: privacy_profiles.directMessage.pii_pompliant:type_name -> privacy_profiles.pii_compliant
	13, // 9: privacy_profiles.directMessage.pii_violation:type_name -> privacy_profiles.pii_violation
	11, // 10: privacy_profiles.outgoingMessage.indirect:type_name -> privacy_profiles.indirectMessage
	12, // 11: privacy_profiles.outgoingMessage.shared:type_name -> privacy_profiles.sharedMessage
	14, // 12: privacy_profiles.indirectMessage.pii_pompliant:type_name -> privacy_profiles.pii_compliant
	13, // 13: privacy_profiles.indirectMessage.pii_violation:type_name -> privacy_profiles.pii_violation
	14, // 14: privacy_profiles.sharedMessage.pii_pompliant:type_name -> privacy_profiles.pii_compliant
	13, // 15: privacy_profiles.sharedMessage.pii_violation:type_name -> privacy_profiles.pii_violation
	0,  // 16: privacy_profiles.pii_violation.pii:type_name -> privacy_profiles.PII_type
	0,  // 17: privacy_profiles.pii_compliant.pii:type_name -> privacy_profiles.PII_type
	5,  // 18: privacy_profiles.purposeBasedProcessing.ProcessingEntriesEntry.value:type_name -> privacy_profiles.dataItemAndThirdParties
	6,  // 19: privacy_profiles.dataItemAndThirdParties.EntryEntry.value:type_name -> privacy_profiles.thirdParties
	3,  // 20: privacy_profiles.PrivacyProfileComposer.PostObservedProfile:input_type -> privacy_profiles.SvcObservedProfile
	17, // 21: privacy_profiles.PrivacyProfileComposer.GetSystemWideProfile:input_type -> google.protobuf.Empty
	17, // 22: privacy_profiles.PrivacyProfileComposer.PostObservedProfile:output_type -> google.protobuf.Empty
	2,  // 23: privacy_profiles.PrivacyProfileComposer.GetSystemWideProfile:output_type -> privacy_profiles.SystemwideObservedProfile
	22, // [22:24] is the sub-list for method output_type
	20, // [20:22] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_privacy_profiles_proto_init() }
func file_privacy_profiles_proto_init() {
	if File_privacy_profiles_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_privacy_profiles_proto_rawDesc), len(file_privacy_profiles_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_privacy_profiles_proto_goTypes,
		DependencyIndexes: file_privacy_profiles_proto_depIdxs,
		EnumInfos:         file_privacy_profiles_proto_enumTypes,
		MessageInfos:      file_privacy_profiles_proto_msgTypes,
	}.Build()
	File_privacy_profiles_proto = out.File
	file_privacy_profiles_proto_goTypes = nil
	file_privacy_profiles_proto_depIdxs = nil
}
