name: Push OPA Bundle service image to Docker Hub

on:
  push:
    tags:
      - opa/v**

jobs:
  push_opa_to_registry:
    name: Push OPA Bundle service image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/dettanym/prose-opa
          tags: |
            type=match,pattern=opa/(v\d.\d.\d),group=1

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: opa
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
