name: Push Presidio service image to Docker Hub

on:
  push:
    tags:
      - presidio/v**

jobs:
  push_opa_to_registry:
    name: Push Presidio service image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/dettanym/prose-presidio
          tags: |
            type=match,pattern=presidio/(v\d.\d.\d),group=1

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: presidio
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
